apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: {{ template "appname" .}}
  name: {{ template "appname" .}}-metrics-service
  namespace: classes-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: {{ template "appname" .}}
