# kind: HorizontalPodAutoscaler 
# apiVersion: autoscaling/v2beta2 
# metadata:
#   name: {{ template "appname" .}}
# spec:
#   scaleTargetRef: 
#     apiVersion: argoproj.io/v1alpha1
#     kind: Rollout
#     name: {{ template "appname" .}}
#   minReplicas: 1
#   maxReplicas: 1
#   behavior:
#   metrics: 
#   - type: Resource 
#     resource: 
#       name: cpu
#       target: 
#         type: Utilization
#         averageUtilization: 50