apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: school
spec:
  hosts:
  - "*"
  gateways:
  - main-gateway
  http:
  - match:
    - uri:
        regex: /classes
    - uri:
        regex: /classes/.*
    route:
    - destination:
        host: classes-school-manager-api.classes-system
        port:
          number: 80
  - match:
    - uri:
        regex: /students
    - uri:
        regex: /students/.*
    route:
    - destination:
        host: students-school-manager-api.students-system
        port:
          number: 80