apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  {{ template "appname" .}}-role
subjects:
- kind: ServiceAccount
  name: {{ template "appname" .}}-sa
  namespace: {{ template "namespace" .}}
