apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: classes-api-vs
  namespace: classes-system
spec:
  hosts:
  - "*"
  gateways:
  - main-gateway
  http:
  - match:
    - uri:
        exact: /classes
    - uri:
        regex: /classes/.*
    route:
    - destination:
        host: classes-school-manager-api.classes-system.svc.cluster.local
        port:
          number: 80