apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: students-school-manager-controller
  name: students-school-manager-controller-metrics-service
  namespace: students-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: students-school-manager-controller
